name: Video Watermark

on:
  workflow_dispatch:

jobs:
  watermark:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Check FFmpeg
        run: |
          ffmpeg -version
